# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e0e7705a82075f90b94342ab4cbf19fcf574332111bd777c7d63ec53e240efb6a7e0f62f3144ded20c378e45961d21cb2fb734f813b13ed46b198949bb605b9

test:
  secret_key_base: e4d937f425267efdbe6fe87faca931f1015a804699582f2d57dccea7703cbc363609d162b18759482bbcc3e1ef795e83d86f2d6919961040a7860d7efe9102eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
